sonar.projectKey=HoltzTomas_sonarcloud-repsol-demo
sonar.organization=holtztomas
sonar.projectName=Contract API (Sonar remediation demo)

sonar.sources=cmd,internal,infra
sonar.exclusions=**/*_test.go,data/**
sonar.go.exclusions=**/vendor/**
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
